DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
is_available BOOLEAN NOT NULL,
request_id BIGINT,
owner_id BIGINT
);

CREATE TABLE IF NOT EXISTS booking (
booking_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
start_time TIMESTAMP WITHOUT TIME ZONE,
end_time TIMESTAMP WITHOUT TIME ZONE,
item_id BIGINT,
user_id BIGINT,
status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS comments (
comments_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
text VARCHAR(255) NOT NULL,
item_id BIGINT,
author_id BIGINT,
created TIMESTAMP WITHOUT TIME ZONE
);